INSERT INTO aswindle.Department VALUES(1,'registration',171);
INSERT INTO aswindle.Department VALUES(2,'finance',172);
INSERT INTO aswindle.Department VALUES(3,'emergency',1);
INSERT INTO aswindle.Department VALUES(4,'surgery',8);
INSERT INTO aswindle.Department VALUES(5,'oncology',4);
INSERT INTO aswindle.Department VALUES(6,'cardiology',5);
INSERT INTO aswindle.Department VALUES(7,'pediatrics',6);
INSERT INTO aswindle.Department VALUES(8,'nursing',7);
INSERT INTO aswindle.Department VALUES(9,'pharmacy',2);
